name: CI

on:
  push:
  pull_request:
jobs:
  install_with_pip3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install with pip3
        run: |
          pip3 install .
          pip3 show bubop
  unittests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      # python/poetry setup
      - uses: actions/checkout@v2
      - name: Setup poetry
        uses: abatilo/actions-poetry@v3.0.2
        with:
          poetry-version: "1.7.1"
          # poetry-plugins: "poetry-dynamic-versioning[plugin]"
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install python dependencies
        run: |
          poetry install --all-extras

      # run tests
      - name: Run tests
        run: poetry run pytest
  style_and_linters:
    runs-on: ubuntu-latest
    steps:
      # python/poetry setup
      - uses: actions/checkout@v2
      - name: Setup poetry
        uses: abatilo/actions-poetry@v3.0.2
        with:
          poetry-version: "1.7.1"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: poetry
      - name: Install python dependencies
        run: |
          poetry install --all-extras

      # run pre-commit
      - run: poetry run pre-commit run --all-files
  coverage:
    runs-on: ubuntu-latest
    steps:
      # python/poetry setup
      - uses: actions/checkout@v2
      - name: Setup poetry
        uses: abatilo/actions-poetry@v3.0.2
        with:
          poetry-version: "1.7.1"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: poetry
      - name: Install python dependencies
        run: |
          poetry install --all-extras

      # run coverage
      - name: Coverage
        run: |
          poetry run coverage run -m pytest --doctest-modules
          poetry run coverage report
      - name: Coveralls
        run: poetry run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  publish_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish package to pypi
        uses: JRubics/poetry-publish@v2.0
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
