name: "Publish to PyPI"
on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags:
      - "*"

jobs:
  call-workflow-audit:
    uses: ./.github/workflows/install.yml
  call-workflow-build:
    uses: ./.github/workflows/lint_and_test.yml
  call-workflow-build-docs:
    uses: ./.github/workflows/unittest.yml
  publish_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup poetry
        uses: abatilo/actions-poetry@v3.0.2
        with:
          poetry-version: "2.1.3"
          poetry-plugins: "poetry-dynamic-versioning[plugin]"
      - name: Call poetry publish
        run: |
          poetry publish --build --no-interaction
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
